version: '3.8'
services:
  haproxy:
    image: docker.io/brycelarge/haproxy:latest
    container_name: haproxy
    restart: unless-stopped
    network_mode: host  # Optional: Use host networking if needed
    ports:
      - "80:80"
      - "443:443/tcp"
      - "8443:8443/udp"
    volumes:
      - ./data:/config
      - ./data/logs:/var/log/haproxy
      - ./data/deployed-certs:/etc/haproxy/certs
    environment:
      - MIXED_SSL_MODE=true
      - HA_DEBUG=false
      - HAPROXY_THREADS=16
      - CONFIG_AUTO_GENERATE=true
      - ACME_CHALLENGE_TYPE=http
      - ACME_EMAIL=your-email@example.com
    healthcheck:
      test: ["CMD", "/scripts/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    security_opt:
      - no-new-privileges:true