name: haproxy

services:
  haproxy:
    image: brycelarge/haproxy:latest
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    platform: linux/amd64
    container_name: haproxy
    volumes:
      - ./config:/config
      - /var/log/haproxy:/var/log/haproxy
    environment:
      # Core Settings
      - HAPROXY_THREADS=4
      - HAPROXY_BIND_IP=0.0.0.0
      - CONFIG_AUTO_GENERATE=false
      - MIXED_SSL_MODE=true
      - HA_DEBUG=false

      # QUIC/HTTP3 Settings
      - H3_29_SUPPORT=true
      - QUIC_MAX_AGE=86400

      # ACME/SSL Settings
      - ACME_EMAIL=your-email@example.com

    ports:
      # HTTP
      - "80:80"
      # HTTPS
      - "443:443"
      # QUIC/UDP
      - "8443:443/udp"
    
    healthcheck:
      test: ["CMD", "/scripts/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    driver: bridge