#!/usr/bin/with-contenv bash
# shellcheck shell=bash

source /scripts/acme_functions.sh

mkdir -p /config/acme/tls1-params \
    /config/acme/certs

if [ ! -e /config/acme/tls1-params/ffdhe2048 ]; then
    echo "[acme] Getting recommended Diffie-Hellman params for TLS1.3" | ts '%Y-%m-%d %H:%M:%S'
    curl -s "https://ssl-config.mozilla.org/ffdhe2048.txt" > /config/acme/tls1-params/ffdhe2048
    chown acme:acme /config/acme/tls1-params/ffdhe2048
    chmod 644 /config/acme/tls1-params/ffdhe2048
fi

if [ ! -e /config/acme/acme.sh.env ]; then
    install_acme;
fi

if [ ! -d /config/acme/ca ]; then
    register_acme
else
    verify_cron
fi