#!/usr/bin/with-contenv bash
# shellcheck shell=bash

source /scripts/acme_functions.sh # issue_cert and deploy_cert functions
source /scripts/debug.sh

ACME_THUMBPRINT="/config/acme/ca/thumbprint"

# Path to HAProxy certificates
HAPROXY_CERTS_DIR="/etc/haproxy/certs"

# Path to ACME certificates (adjust if needed)
ACME_CERTS_DIR="/config/acme/certs"

# Loop until both files exist
while [ ! -f "$ACME_THUMBPRINT" ]; do
    echo "[acme] waiting for $ACME_THUMBPRINT to be created before setting up acme..." | ts '%Y-%m-%d %H:%M:%S'
    sleep 3
done

echo "[acme] waiting for 15 seconds before starting to parse and issue certificates..." | ts '%Y-%m-%d %H:%M:%S'
sleep 15; # make sure haproxy is up and stable

check_for_missing_domain_certs